# NOTE: Ports should be specified in docker-compose.override.yml
version: "3.9"
services:
  lilac:
    image: lilac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  mirrorball:
    image: mirrorball
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  doughnut:
    image: doughnut
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
